---
language: ruby
rvm:
- 2.2.2
- ruby-head
allow_failures:
  rvm:
  - ruby-head
before_script:
- "./bin/setup"
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
gemfile:
- gemfiles/rails_4.2.10_active_admin_1.2.1.gemfile
- gemfiles/rails_3.2.22.5_active_admin_1.0.0.pre5.gemfile
addons:
  code_climate:
    repo_token: c326cca5984d0e32d2c6b5d9b985756ee9312f63fc6a9480fc9cfa55c454d68a
